name: Run Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: swift:6.0
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Swift dependencies
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.cache/org.swift.swiftpm
          key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift', 'Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-

      - name: Build project
        run: swift build --configuration debug

      - name: Run unit tests
        run: swift test --parallel
        timeout-minutes: 10

      - name: Test CLI tool
        run: |
          # Build the CLI tool
          swift build -c release --product ipascanner
          
          # Test help command
          ./.build/release/ipascanner --help
          
          echo "✅ CLI tool test completed"

      - name: Test results summary
        if: always()
        run: |
          echo "✅ Tests completed"
          echo "📊 Test suite run successfully"